AcrossTheCloud/TBA21-client

- src/components/pages/user/Login.tsx
- src/components/pages/user/SignUp.tsx
Removed isSignUp from state in Login and Signup and passed in true/false to FacebookButton instead
> OC-15 removed signup state

- src/components/pages/admin/people/ManageUsers.tsx
- src/components/pages/user/AccountConfirmation.tsx
- src/components/pages/user/ResetPassword.tsx
- src/components/utils/inputs/input.ts
OC-44 Missed backticks in symbols check.
Also fixed a bunch of linter warnings.
> OC-42 Pop overs on the two icons on manageusers

- src/components/map/DraggableMap.test.tsx
- src/components/map/DraggableMap.tsx
Some example testing of componentDidMount, checking state & props and finally checking two input fields on the DOM.
> OC58 - Example Testing, Draggable Map.

- src/components/admin/utils/ShortPaths.tsx
- src/components/metadata/CollectionEditor.tsx
- src/components/metadata/ItemEditor.tsx
- src/components/metadata/fields/YearSelect.tsx
- src/components/utils/react-select.ts
- src/components/utils/slugify.ts
- src/styles/base/icons.scss
Short paths for item and collection editor.
> Oc 188 editor shortpath input checker

- src/components/utils/AudioPlayer.tsx
This one is for you @matthewberryman
> Fixed the ghastly red audio player

- src/actions/searchConsole.tsx
- src/components/search/SearchConsole.tsx
> Oc 202 front end design

- src/components/metadata/FileUpload.tsx
for consistency with other code
> set s3 key uuid to be based on user pool uuid

- src/actions/pages/privacyPolicy.ts
- src/actions/searchConsole.tsx
- src/components/Home.tsx
- src/components/PrivacyPolicyPopUp.tsx
- src/components/pages/PrivacyPolicy.tsx
- src/components/pages/TermsAndConditions.tsx
- src/components/search/SearchConsole.tsx
- src/reducers/index.tsx
- src/reducers/pages/privacyPolicy.ts
- src/reducers/searchConsole.tsx
- src/router.tsx
- src/styles/components/search/searchConsole.scss
- src/styles/layout/buttons.scss
- src/styles/layout/privacyPolicyPopUp.scss
> Search + cookie

- src/components/Home.tsx
- src/components/layout/Footer.tsx
- src/components/pages/About.tsx
- src/components/pages/TermsAndConditions.tsx
- src/styles/layout/footer.scss
- src/styles/layout/logo.scss
https://acrossthecloud.atlassian.net/browse/OC-310
> Oc 310 about bar

- src/components/item/ViewItem.tsx
Change region and venue label to conditional that adds the s
> OC-337 Added directors and collaborators for Video item types

- src/components/item/ViewItem.tsx
Show director/collaborator on item view page regardless of the object category
> Show director/collaborator on item view page regardless of the object category

- package-lock.json
- package.json
- src/components/admin/utils/DraggableMap.test.tsx
- src/components/admin/utils/DraggableMap.tsx
- src/components/map/controls/Search.tsx
- src/components/map/map.tsx
- src/components/map/utils/initialiseMap.ts
- src/components/map/utils/initialiseMarkerCluster.ts
- src/components/map/utils/progressBar.ts
- src/styles/components/map/map.scss
Added North Star ocean style to the map.
> OC-357 Ocean Style

- src/components/Home.tsx
Mobile + tablet not showing correct amount.
> Staging to dev OC-331

- src/components/layout/Header.tsx
- src/router.tsx
Router /admin /contributor redirects to login page if the user isn't logged in.
> Master to staging.

- src/components/layout/Header.tsx
- src/router.tsx
Router /admin /contributor redirects to login page if the user isn't logged in.
> Master to dev.

- src/styles/components/pages/viewItem.scss
OC-381 added css to carousel controls to stop the controls taking up half the page
> OC-381 video diversion issue

- src/components/layout/HomepageVideo.tsx
- src/components/metadata/CollectionEditor.tsx
Collection editor Accept License was showing even if the user accepted it.
Homepage video removed console log and camelCased playsinline (playsInline)
> OC-387 Collection Editor and Homepage video fix.

- src/components/metadata/withCollapse.tsx
OC-407 - Puts stricter null-check on the component
> OC-407 - Puts stricter null-check on the component

- src/components/utils/DetailPreview.tsx
- src/components/utils/PdfPreview.tsx
Looks like no merge conflict; so here is the PR as requested @matthewberryman 
Cheers.
> fixes OC-411

- src/actions/home.tsx
- src/components/collection/ViewCollection.tsx
> fix order in collection view,

- src/styles/components/home.scss
Simply add `width: 100%` to `#body`
> Fix video width not 100% on page load

- something.html
- src/components/collection/ViewCollection.tsx
- src/components/item/ViewItem.tsx
- src/components/metadata/CollectionEditor.tsx
- src/components/metadata/ItemEditor.tsx
- src/components/user/profile/ViewProfile.tsx
- src/components/utils/Share.tsx
- src/styles/base/variables.scss
- src/styles/utils/share.scss
- src/urls.ts
- Update share component to support full text (instead of prefixed with URL)
- Replace all naked string to url builder
> [297]: Links + embed
